<?xml version='1.0'?>

<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="chassisHeight" value="0.1"/>
    <xacro:property name="chassisLength" value="0.4"/>
    <xacro:property name="chassisWidth" value="0.25"/>
    <xacro:property name="chassisMass" value="50"/>

    <xacro:property name="casterRadius" value="0.04"/>
    <xacro:property name="casterMass" value="5"/>

    <xacro:property name="wheelWidth" value="0.05"/>
    <xacro:property name="wheelRadius" value="0.08"/>
    <xacro:property name="wheelPos" value="0.05"/>
    <xacro:property name="wheelMass" value="5"/>

    <xacro:property name="cameraSize" value="0.07"/>
    <xacro:property name="cameraMass" value="0.1"/>

    <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
    <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />

    <link name="footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="footprint"/>
        <child link="chassis"/>
    </joint>

    <link name="chassis">
        <collision> 
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
            <geometry> 
                <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
            </geometry> 
        </collision>
        <visual> 
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
            <geometry> 
                <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
            </geometry> 
            <material name="orange"/>
        </visual>
        <inertial> 
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
            <mass value="${chassisMass}"/> 
            <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
        </inertial>
    </link>

    <joint name="fixed" type="fixed">
        <origin xyz="0 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="caster_wheel"/>
    </joint>

    <link name="caster_wheel">
        <collision>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${casterRadius}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${casterRadius}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <inertial>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <mass value="${casterMass}"/>
            <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
        </inertial>
    </link>

    <link name="left_wheel">
        <collision name="collision">
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
            </geometry>
        </collision>
        <visual name="left_wheel_visual">
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
            <mass value="${wheelMass}"/>
            <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
        </inertial>
    </link>
 
    <link name="right_wheel">
        <collision name="collision">
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
            </geometry>
        </collision>
        <visual name="right_wheel_visual">
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
            <mass value="${wheelMass}"/>
            <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
        </inertial>
    </link>

    <joint type="continuous" name="left_wheel_hinge">
        <origin xyz="${-wheelPos+chassisLength/2} ${wheelWidth/2+chassisWidth/2} ${wheelRadius}" rpy="0 0 0" /> 
        <child link="left_wheel"/>
        <parent link="chassis"/>
        <axis xyz="0 1 0" rpy="0 0 0"/>
        <limit effort="100" velocity="100"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint type="continuous" name="right_wheel_hinge">
        <origin xyz="${-wheelPos+chassisLength/2} -${wheelWidth/2+chassisWidth/2} ${wheelRadius}" rpy="0 0 0" /> 
        <child link="right_wheel"/>
        <parent link="chassis"/>
        <axis xyz="0 1 0" rpy="0 0 0"/>
        <limit effort="100" velocity="100"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint name="hokuyo_joint" type="fixed">
        <axis xyz="0 0 0" />
        <origin xyz="${chassisLength/2-0.05} 0 ${chassisHeight*2-0.04}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="hokuyo"/>
    </joint>

    <link name="hokuyo">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://mybot_description/meshes/hokuyo.dae"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="${cameraMass}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}"/>
        </inertial>
    </link>

</robot>
